### ISSUE TITLE
Token is generated only on session creation

### ISSUE THREAD

**Issue by dariusc93** [martini-contrib/csrf#8]
Something ive noticed when testing this middleware that the token isnt generated unless there is a cookie containing a session. Any reason why?

**Comment by tomsteele** [comment]
Hi @dariusc93, this library follows the encrypted token pattern https://www.owasp.org/index.php/Cross-Site_Request_Forgery_(CSRF)_Prevention_Cheat_Sheet#Encrypted_Token_Pattern which is dependent on a UID value in a session.

The debate as to if you should worry about CSRF on unauthenticated pages isn't something I think we should have here, it's widely debated all over the place and no one seems to agree. I have my own opinions.

If you want to protect from CSRF for anonymous users (users who have not signed in), you can create a session with a random UID value and use that to generate tokens. Hope this helps :smile:

**Comment by dariusc93** [comment]
@tomsteele thanks for the info but it looks like the session (for the token to be generated) has to be the key the "SessionKey". Is that really required or is there a way to generate a token regardless of whatever session is created?

**Comment by tomsteele** [comment]
SessionKey is the key of the key/value pair in the session to used to identified the unique ID. In the examples this is userID, but it can be anything you want. The token is very heavily tied to the Session.
